baseURL = 'https://malrugo.netlify.app/'
languageCode = 'en-us'
title = "Matt's Blog"
theme = 'rocinante'
paginate = 3

[markup]
  [markup.highlight]
    style = "monokailight"
  [markup.goldmark.renderer]
    unsafe= true

[params]
  mainSections = ["posts", "photos"]
  email = "malrugo at icloud"
  favicon = "icons/favicon.png"
  about = """
This blog is a little time capsule to document my days in Mexico, both for myself and for the people I love.
"""

  [[params.links]]
    [[params.links.link]]
      name = "Email"
      href = "/contact"
      smart_email_link = true
    [[params.links.link]]
      name = "Instagram"
      href = "https://www.instagram.com/malrugo_/"
      new_tab = true